apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project_name: loreal_shumera
    dev: Ashok
    Devops: murali
    env: dev
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
    - name: nginx
      image: nginx