apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    #lables
      project_name: loreal
      dev: Ashokreddy
      Devops: murali
      env: prod
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port