apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: loreal
spec:
  selector:
    labels:
      project_name: loreal
      dev: Ashokreddy
      Devops: murali
      env: prod
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
